# Generated by Django 3.2.3 on 2023-09-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkshortener',
            name='short_link',
            field=models.CharField(blank=True, db_index=True, max_length=70, null=True, unique=True),
        ),
    ]
